<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" type="text/css" href="style.css" />
  <title>pzs-ng: Project Zipscript Next Generation (.%country mirror) - disclaimer.</title>
  <script src="piwik.js"></script>
</head>
<body>
<b>DISCLAIMER:</b><br>
<div class="margin1">
    o The tools, programs and sourcecode (from here referred to as 'software') found on www.pzs-ng.eu any of it's official mirrors are for educational purposes only.<br>
    o The software offered can only be downloaded and/or used if not violating any laws in the respective country/countries.<br>
    o The authors of the software, owners of the webservers and their respective ISP's cannot be held responsible for the use or misuse, directly or indirectly, of the content offered.<br>
    o The software offered is work-in-progress, and should be considered as such. There is no guarantee the software will work as expected, desired or even described.<br>
    o Any document or sourcecode that links to this disclaimer, presenting it as such, is covered by these clauses.<br>
    o We use <a href="https://matomo.org/privacy-policy">Matomo</a> free and open source web analytics. Actions are not analysed if your browser is set to send 'Do Not Track' or if you <a href="https://stats.pzs-ng.eu/piwik/index.php?module=CoreAdminHome&action=optOut&language=en&backgroundColor=000&fontColor=BBB&fontSize=13px&fontFamily=Courier%20New">opt-out</a>.<br>
    o Should any part of this disclaimer be unclear, please contact us by email at <a href="mailto:disclaimer@pzs-ng.eu">disclaimer@pzs-ng.eu</a> for further explanations. We might even read it, eventually... or maybe not.<br>
</div>
<br>
Back to <a href="http://%country.pzs-ng.com">our website</a>.<br>
Meet us at <a target=_blank href="http://www.efnet.org">EFnet</a> channel #pzs-ng<br>
Page generated by <a href='https://github.com/pzs-ng/scripts'>template-mirror</a> at %time_of_generation.<br>
<!-- Matomo Image Tracker--><noscript>
<img src="https://stats.pzs-ng.eu/piwik/piwik.php?idsite=18&rec=1" style="border:0" alt="" />
</noscript><!-- End Matomo -->
</body>
</html>
