<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" type="text/css" href="style.css"/>
  <title>pzs-ng: Project Zipscript Next Generation</title>
  <script src="piwik.js"></script>
</head>
<body>
Welcome to pzs-ng (Project Zipscript - Next Generation) <b>quotes</b><br>
<div class="margin3">main page: <a href="index.html">index.html</a> | <a href="quotes.html">quotes.html</a> | <a href="stats.html">stats.html</a> | <a href="disclaimer.html">disclaimer.html</a></div><br>
<br>
<b>IRC QUOTES:</b><br>
-----------<br>
<br>
<br>
%quotes
<br>
Meet us at <a target=_blank href="http://www.efnet.org">EFnet</a> channel #pzs-ng<br>
Page generated by <a href='https://github.com/pzs-ng/scripts'>template-mirror</a> at %time_of_generation.<br>
<!-- Matomo Image Tracker--><noscript>
<img src="https://stats.pzs-ng.eu/piwik.php?idsite=18&rec=1" style="border:0" alt="" />
</noscript><!-- End Matomo -->
</body>
</html>
