<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
  <link rel="stylesheet" type="text/css" href="index.css"/>
  <title>pzs-ng: Project Zipscript Next Generation</title>
  <script src="piwik.js"></script>
</head>
<body>
Welcome to pzs-ng (Project Zipscript - Next Generation) <b>quotes</b><br>
<div class="mirror_links">main page: <a href="index.html">index.html</a></div><br><br>
%quotes
<br>
Meet us at <a target=_blank href="http://www.efnet.org">EFnet</a> channel #pzs-ng<br>
Page generated by <a href='https://github.com/pzs-ng/scripts'>template-mirror</a> at %time_of_generation.<br>
<!-- Matomo Image Tracker--><noscript>
<img src="https://stats.pzs-ng.eu/piwik/piwik.php?idsite=18&rec=1" style="border:0" alt="" />
</noscript><!-- End Matomo -->
</body>
</html>
