name: create-quotes

on:
  push:
    paths:
      - 'quotes'
    branches: [ master ]
  pull_request:
    paths:
      - 'quotes'
    branches: [ master ]
  workflow_dispatch:

env:
  GIT_USER_NAME: github-actions[bot]
  GIT_USER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    #outputs:
    #  quotes: ${{ steps.changes.outputs.quotes }}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          #echo "::set-output name=quotes::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep quotes$ | xargs)"
          echo "::set-output name=quotes::$(git diff --name-only --diff-filter=ACMRT HEAD^ ${{ github.sha }} | grep quotes$ | xargs)"
  generate_quotes:
    # require the first job to have ran
    needs: changedfiles
    # only run there are changed files
    if: ${{needs.changedfiles.outputs.quotas}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: debug
        run: |
          echo "DEBUG: changedfiles=${{needs.changedfiles.outputs.quotas}}"
          #echo "DEBUG: git log"
          #git  --no-pager log --pretty=oneline -10
          #echo "DEBUG: git diff"
          #git diff --name-status HEAD~1 -- 
      - name: template-mirror-mini
        run: ./scripts/template-mirror/tmm.pl
