# This is a basic workflow to help you get started with Actions

name: create-quotes

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  gen_quotes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: template-mirror-mini
        run: ./scripts/template-mirror/tmm.pl
