name: create-quotes

on:
  push:
    paths:
      - 'quotes'
    branches: [ master ]
  pull_request:
    paths:
      - 'quotes'
    branches: [ master ]
  workflow_dispatch:

env:
  GIT_USER_NAME: github-actions[bot]
  GIT_USER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com

jobs:
  generate_quotes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      #- name: debug
      #  run: |
      #    echo "DEBUG: diff"
      #    git diff --name-only --diff-filter=ACMRT HEAD^ -- quotes
      #    echo "DEBUG: git log"
      #    git  --no-pager log --pretty=oneline -10
      #    echo "DEBUG: git diff"
      #     git diff --name-status HEAD~1 -- 
      - name: template-mirror-mini
        run: |
          git diff --name-only --diff-filter=ACMRT HEAD^ -- quotes && \
          ./scripts/template-mirror/tmm.pl
